id: P009304
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS17299
  title: དབུ་མ་འཇུག་པ།
  author: ''
  volumes:
    a1f572efd1e643aebbcdc01965ad9cc1:
      image_group_id: I8LS17317
      title: ''
      volume_number: 1
      total_pages: 64
      base_file: v001.txt
